//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinnabon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string SECOND_NAME { get; set; }
        public string EMAIL { get; set; }
        public string PHONE { get; set; }
        public string DEPARTMENT { get; set; }
        public decimal SALARY { get; set; }
        public int HOURS { get; set; }
        public string USER_NAME { get; set; }
        public string PASSWORD { get; set; }
        public string POSITION { get; set; }
        public byte[] PHOTO { get; set; }
        public System.DateTime DATE { get; set; }
    }
}
